In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("Bengaluru_House_Data.csv")

In [4]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
df.info

<bound method DataFrame.info of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>

In [7]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [8]:
df.isnull()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...
13315,False,False,False,False,False,False,False,False,False
13316,False,False,False,False,True,False,False,True,False
13317,False,False,False,False,False,False,False,False,False
13318,False,False,False,False,False,False,False,False,False
13319,False,False,False,False,True,False,False,False,False

In [10]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [17]:
df1=df.dropna()

In [24]:
df1['bhk'] = df1['size'].apply(lambda x: int(x.split(' ')[0]))

In [25]:
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00,4

In [26]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

# هيعرض لك بس الصفوف اللي المساحة فيها مش رقم عادي (زي الـ Range)
df1[~df1['total_sqft'].apply(is_float)].head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.000,4
122,Super built-up Area,18-Mar,Hebbal,4 BHK,SNontle,3067 - 8156,4.0,0.0,477.000,4
137,Super built-up Area,19-Mar,8th Phase JP Nagar,2 BHK,Vaarech,1042 - 1105,2.0,0.0,54.005,2
165,Super built-up Area,18-Dec,Sarjapur,2 BHK,Kinuerg,1145 - 1340,2.0,0.0,43.490,2
188,Super built-up Area,Ready To Move,KR Puram,2 BHK,MCvarar,1015 - 1540,2.0,0.0,56.800,2
549,Super built-up Area,18-Sep,Hennur Road,2 BHK,Shxorm,1195 - 1440,2.0,0.0,63.770,2
661,Super built-up Area,Ready To Move,Yelahanka,2 BHK,Rarthne,1120 - 1145,2.0,0.0,48.130,2
672,Built-up Area,18-Mar,Bettahalsoor,4 Bedroom,Toainnt,3090 - 5002,4.0,0.0,445.000,4
772,Super built-up Area,20-Dec,Banashankari Stage VI,2 BHK,Brens7,1160 - 1195,2.0,0.0,59.935,2
850,Super built-up Area,22-Dec,Bannerghatta Road,2 BHK,PrarePa,1115 - 1130,2.0,0.0,58.935,2

In [27]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

# دلوقتي هنطبق الوظيفة دي على العمود كله في نسخة جديدة من البيانات
df3 = df1.copy()
df3['total_sqft'] = df3['total_sqft'].apply(convert_sqft_to_num)

In [30]:
df3.loc[30],df3.loc[122]

(area_type       Super built-up  Area
 availability                  19-Dec
 location                   Yelahanka
 size                           4 BHK
 society                      LedorSa
 total_sqft                    2475.0
 bath                             4.0
 balcony                          0.0
 price                          186.0
 bhk                                4
 Name: 30, dtype: object,
 area_type       Super built-up  Area
 availability                  18-Mar
 location                      Hebbal
 size                           4 BHK
 society                      SNontle
 total_sqft                    5611.5
 bath                             4.0
 balcony                          0.0
 price                          477.0
 bhk                                4
 Name: 122, dtype: object)

In [31]:
df4 = df3.copy()
df4['price_per_sqft'] = df4['price'] * 100000 / df4['total_sqft']
df4.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4,4615.384615
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3,6245.890861
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2,3247.863248
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4,10592.459605

In [32]:
# 1. تنظيف المسافات
df4.location = df4.location.apply(lambda x: x.strip())

# 2. معرفة عدد البيوت في كل منطقة
location_stats = df4.groupby('location')['location'].agg('count').sort_values(ascending=False)

# 3. تحديد المناطق اللي تكرارها أقل من 10
locations_less_than_10 = location_stats[location_stats <= 10]

# 4. تحويل المناطق دي لـ "other"
df4.location = df4.location.apply(lambda x: 'other' if x in locations_less_than_10 else x)

# نشوف بقوا كام منطقة دلوقتي
len(df4.location.unique())

144

In [33]:
# بنشيل أي شقة مساحتها الكلية مقسومة على عدد الأوض (bhk) أقل من 300
df5 = df4[~(df4.total_sqft/df4.bhk < 300)]
df5.shape

(7454, 11)

In [34]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft) # المتوسط
        st = np.std(subdf.price_per_sqft) # الانحراف المعياري
        # بنحتفظ بس بالبيانات اللي قريبة من المتوسط
        reduced_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out

df6 = remove_pps_outliers(df5)
df6.shape

(5862, 11)

In [35]:
# بنشيل أي شقة فيها حمامات أكتر من (عدد الأوض + 2)
df7 = df6[df6.bath < df6.bhk + 2]
df7.shape

(5808, 11)

In [36]:
# حذف الأعمدة اللي مش محتاجينها
df8 = df7.drop(['size', 'price_per_sqft', 'society', 'balcony', 'availability', 'area_type'], axis='columns')
df8.head()

             location  total_sqft  bath  price  bhk
0  1st Phase JP Nagar      2825.0   4.0  250.0    4
1  1st Phase JP Nagar      1875.0   3.0  167.0    3
2  1st Phase JP Nagar      1394.0   2.0  100.0    2
3  1st Phase JP Nagar      1077.0   2.0   93.0    2
4  1st Phase JP Nagar      1590.0   3.0  131.0    3

In [37]:
# 1. تحويل المناطق لأعمدة أرقام
dummies = pd.get_dummies(df8.location)

# 2. دمج الأعمدة الجديدة مع الجدول الأصلي وحذف عمود الـ "other" (عشان نتجنب مشكلة Dummy Variable Trap)
df9 = pd.concat([df8, dummies.drop('other', axis='columns')], axis='columns')

# 3. حذف عمود الـ location الأصلي لأننا خلاص حولناه لأرقام
df10 = df9.drop('location', axis='columns')

df10.head()

,total_sqft,bath,price,bhk,1st Phase JP Nagar,5th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,9th Phase JP Nagar,AECS Layout,...,Thubarahalli,Tumkur Road,Uttarahalli,Varthur,Vijayanagar,Vittasandra,Whitefield,Yelahanka,Yelahanka New Town,Yeshwanthpur
0,2825.0,4.0,250.0,4,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1875.0,3.0,167.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1394.0,2.0,100.0,2,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1077.0,2.0,93.0,2,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1590.0,3.0,131.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [38]:
X = df10.drop('price', axis='columns') # كل الأعمدة ماعدا السعر
y = df10.price # عمود السعر فقط

In [39]:
from sklearn.model_selection import train_test_split

# بنقسم البيانات: 80% تدريب و 20% اختبار
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [40]:
     from sklearn.linear_model import LinearRegression

lr_clf = LinearRegression()
lr_clf.fit(X_train, y_train) # هنا الموديل "بيذاكر" البيانات

# قياس الدقة
lr_clf.score(X_test, y_test)

0.8912604894017805

In [41]:
def predict_price(location, sqft, bath, bhk):    
    loc_index = np.where(X.columns == location)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk
    if loc_index >= 0:
        x[loc_index] = 1

    return lr_clf.predict([x])[0]

In [42]:
predict_price('1st Phase JP Nagar', 1000, 2, 2)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(99.29225065384101)

In [43]:
predict_price('Indira Nagar', 1000, 2, 2)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(123.75075962656068)

In [44]:
import pickle
import json

# 1. حفظ الموديل
with open('banglore_home_prices_model.pickle','wb') as f:
    pickle.dump(lr_clf, f)

# 2. حفظ أسماء الأعمدة
columns = {
    'data_columns' : [col.lower() for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(df8.total_sqft, df8.price, color='blue', marker='+', alpha=0.5)
plt.xlabel("Total Square Feet Area")
plt.ylabel("Price (Lakh Indian Rupees)")
plt.title("Area vs Price Distribution")
plt.show()